name: Node.js CI
on:
  pull_request:
    branches: master
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
          cache-dependency-path: ./starter/frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./starter/frontend
      - name: Run lint
        run: npm run lint
        working-directory: ./starter/frontend
    continue-on-error: false
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
          cache-dependency-path: ./starter/frontend/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend
      - name: Run test
        run: npm run test
        working-directory: ./starter/frontend
    continue-on-error: false
  
    

